[Variables]
IconSize=90
CurrentIconConfig=NONE
CurrentTheme=Wave

ChromeLocation=chrome.exe
ExcelLocation=excel.exe
FirefoxLocation=C:\Program Files (x86)\Mozilla Firefox\firefox.exe
FolderLocation=Documents
GIMPLocation=C:\Program Files\GIMP 2\bin\gimp-2.8.exe
HearthstoneLocation=C:\Program Files (x86)\Hearthstone\Hearthstone Beta Launcher.exe
IntelliJLocation=intellij.exe
NotepadLocation=notepad.exe
PowerpointLocation=powerpoint.exe
RainmeterLocation=C:\Program Files\Rainmeter\Rainmeter.exe
SettingsLocation=settings.exe
SpotifyLocation=spotify.exe
SteamLocation=steam.exe
TorLocation=tor.exe
WordLocation=word.exe

[Script]
Measure=Script
ScriptFile="#@#\AutoScript.lua"
